### ISSUE TITLE
gradlew debugXml fails for example8Jobs.groovy

### ISSUE THREAD

**Issue by astolz67** [sheehan/job-dsl-gradle-example#35]
Hi,
when executing: ./gradlew debugXml -Dpattern=jobs/**/*Jobs.groovy, the following error is thrown:
Exception in thread "main" javaposse.jobdsl.dsl.DslScriptException: (script, line 19) No signature of method: javaposse.jobdsl.dsl.helpers.triggers.TriggerContext.githubPullRequest() is applicable for argument types: (script$_run_closure2_closure4_closure8) values: [script$_run_closure2_closure4_closure8@74cadd41]
Do you have any idea how to get this running locally? It works if executed in Jenkins.
Thanks and best regards,
Andreas

**Comment by sheehan** [comment]
It looks like the syntax changed in v1.43. See https://github.com/jenkinsci/job-dsl-plugin/blob/f9549001c8b1fed526a9d588e6c9eaca58693f66/docs/Migration.md#github-pull-request-builder

I've updated the example to use the new syntax. 

Fixed by https://github.com/sheehan/job-dsl-gradle-example/commit/92e70798ad163cd2314693113ce35414f3d34d8a

**Comment by astolz67** [comment]
Thanks a lot for looking into it.
Sorry to bother, but since 1.43 it's githubPullRequest, prior to 1.43 pullRequest.
Thus, the following warning is thrown:
Warning: (script, line 19) pullRequest is deprecated.
Any idea?
