### ISSUE TITLE
debugXml task has been removed

### ISSUE THREAD

**Issue by SchwingSK** [sheehan/job-dsl-gradle-example#73]
Not really a bug, but I didn't find a mailing list to ask this. Don't hesitate to close & redirect me to the correct channel.

It seems to be related to #42 and debugXml was replaced by running the test task, which works nicely but:

1. is really slow (4s vs 34s on my setup). Modifying & testing a script is now less fluid than before
2. doesn't display as much information in the console (we have to open the JUnit report to see the error/warnings)

AFAIK, 1 comes from running an actual instance of Jenkins to support Generated DSLs, so if I don't use Generated DSLs, can I still use the debugXml task without risks? (I patched the old XmlOutputRunner and it seems to work ok).

For 2, setting the `testLogging.showStandardStreams = true` in the test task solves the issue (although we get Jetty's output too, but I can live with that)

**Comment by sheehan** [comment]
Yeah the only reason I removed it was because it can't support the Generated DSLs, which is the new way going forward. If you're not using and of those methods yet than you should be ok to keep using it.

**Comment by CaptainCamelCase** [comment]
I have another question, don't know if this is the right thread but please correct me otherwise.

When I generate using the latest example config where a Jenkins instance is fired up, it not only takes a lot longer time to generate, ~1600 generated jobs takes about 4 min using Jenkins vs. 1.30 min directly through a JVM (debugXml), but also the generated xml files differ slightly.

Does anyone here know the reason why, and is it fixable?

**Comment by sheehan** [comment]
@CaptainCamelCase do you have an example of how do they differ?

**Comment by CaptainCamelCase** [comment]
@sheehan When I switch and run it through a JDK8 JVM (instead of through Jenkins) it changes various things like quotation style, xml tag endings and git submodule options, as seen in the attached picture.

![job-dsl-jenkins-diff](https://cloud.githubusercontent.com/assets/22143839/23664705/935a40a8-0356-11e7-9671-64a7c9cc9719.png)

**Comment by sheehan** [comment]
It looks like those are generated with two different Job DSL versions. `reference` and `timeout` were removed at some point. The quotation style and XML tag endings must be configurable somewhere.
